Update SyncFork.yml

diff --git a/.github/workflows/SyncFork.yml b/.github/workflows/SyncFork.yml
--- a/.github/workflows/SyncFork.yml
+++ b/.github/workflows/SyncFork.yml
@@ -1,16 +1,34 @@
-name: Sync Fork
+name: Upstream Sync
+
+permissions:
+    contents: write
 
 on:
-  push: # push 时触发, 主要是为了测试配置有没有问题
-  schedule:
-    - cron: '* */24 * * *' # 每天一次
+    schedule:
+        - cron: "0 0 * * *"
+    workflow_dispatch:
+
 jobs:
-  repo-sync:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: tgymnich/fork-sync@v1.8
-        with:
-          token: ${{ secrets.TOKEN }} #Github Token，记得加入secrets
-          owner: blinko-space # fork 的上游仓库 user
-          head: main # fork 的上游仓库 branch
-          base: main # 本地仓库 branch
+    sync_with_upstream:
+        name: Sync with Upstream
+        runs-on: ubuntu-latest
+        if: ${{ github.event.repository.fork }}
+
+        steps:
+            - name: Checkout target repo
+              uses: actions/checkout@v3
+
+            - name: Sync Upstream
+              uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
+              with:
+                  target_repo_token: ${{ secrets.TOKEN }}
+                  upstream_sync_repo: blinko-space/blinko
+                  upstream_sync_branch: main
+                  target_sync_branch: main
+                  test_mode: false
+
+            - name: Check for Failure
+              if: failure()
+              run: |
+                  echo "[Error] Due to a change in the workflow file of the upstream repository, GitHub has automatically suspended the scheduled automatic update. You need to manually sync your fork."
+                  exit 1
